version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-5
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"

  php:
    build: ./docker/php
    container_name: php
    ports: ["9000:9000"]
    volumes: ["./symfony/:/var/www/symfony:cached"]
    command: ["php", "-S", "127.0.0.1:9090", "-t", "var/www/public"]


  nginx:
    build: ./docker/nginx
    container_name: ngin
    ports: ["81:81"]
    volumes: ["./symfony/:/var/www/symfony:cached"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmi
    depends_on:
      - mysql
    ports:
      - 8085:80
    environment:
      MYSQL_USERNAME: user
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
